// example2 — a polished report, to show WHY Typst.
// Everything decorative below (title band, stat cards, striped table,
// callout, two-column text) is a handful of lines each. Try that in LaTeX.
//
// We import tweave for its math shorthands but skip its document template —
// this file styles itself, to show you're never locked in.
//
// Convention: the rendered PDF reads as a straight report on the cars.
// All commentary about tweave/Typst lives in comments like this one, so
// read the source alongside the PDF for the tour.

#import "@local/tweave:0.1.0": iid, bar, Normal

#set page(
  paper: "us-letter", margin: (x: 0.9in, y: 0.9in), numbering: "1",
  // Running header from page 2 onward -- one context expression
  header: context if counter(page).get().first() > 1 [
    #text(9pt, luma(120))[Fuel Economy Report #h(1fr) 1974 _Motor Trend_ data]
    #v(-4pt)
    #line(length: 100%, stroke: 0.4pt + luma(200))
  ],
)
#set text(font: "Libertinus Serif", size: 11pt)
#set math.equation(numbering: "(1)")

#let navy = rgb("#1f3a5f")
#let teal = rgb("#0d7377")

// ---- reusable pieces: 3 lines each --------------------------------------
#let statcard(value, label) = block(
  fill: gradient.linear(navy.lighten(88%), teal.lighten(90%)),
  inset: 12pt, radius: 6pt, width: 100%,
)[#text(22pt, weight: "bold", navy)[#value] \ #text(9pt, luma(90))[#upper(label)]]

#let keyfinding(stat, body) = block(
  fill: teal.lighten(88%), stroke: (left: 4pt + teal),
  inset: 14pt, radius: 6pt, width: 100%,
)[#grid(columns: (auto, 1fr), gutter: 16pt, align: horizon,
  text(26pt, weight: "bold", teal.darken(20%))[#stat], body)]

#let note(body) = block(
  fill: rgb("#fff8e1"), stroke: (left: 3pt + rgb("#f9a825")),
  inset: 10pt, radius: 3pt, width: 100%,
)[#text(size: 10pt)[#body]]

#show heading.where(level: 1): it => block(above: 1.6em)[
  #text(navy, weight: "bold")[#it.body]
  #box(width: 1fr, line(length: 100%, stroke: 0.5pt + navy.lighten(50%)))
]

// ---- title band ----------------------------------------------------------
#block(width: 100%, inset: (x: 24pt, y: 20pt), radius: 8pt,
  fill: gradient.linear(navy, teal, angle: 30deg),
)[
  #text(white, 26pt, weight: "bold")[Fuel Economy Report]
  #v(2pt)
  #text(white.transparentize(25%), 11pt)[
    1974 _Motor Trend_ road tests · #datetime.today().display("[month repr:long] [year]") · prepared with tweave
  ]
]

```{r, include=FALSE}
# All analysis code is hidden (include=FALSE / echo=FALSE):
# this is a report for readers, not a homework showing work.
set.seed(123)
digits <- 2
data(mtcars)
fit <- lm(mpg ~ wt, data = mtcars)
best <- rownames(mtcars)[which.max(mtcars$mpg)]
```

#v(10pt)

// ---- stat cards: R values inside styled Typst blocks ---------------------
#grid(columns: (1fr, 1fr, 1fr), gutter: 12pt,
  statcard([`r mean(mtcars$mpg)` mpg], [average fuel economy]),
  statcard([`r cor(mtcars$mpg, mtcars$wt)`], [correlation, mpg vs.\ weight]),
  statcard([`r max(mtcars$mpg)` mpg], [best in test: `r best`]),
)

= Weight is the story

Across the `r nrow(mtcars)` cars compiled for _Motor Trend_ by
#cite(<henderson1981>, form: "prose"), fuel economy falls sharply with
vehicle weight. A simple linear model

$ "mpg"_i = beta_0 + beta_1 "weight"_i + epsilon_i, quad epsilon_i iid Normal(0, sigma^2) $

estimates that each additional 1,000 lbs costs about
*`r abs(coef(fit)[2])` mpg* ($R^2 = `r summary(fit)$r.squared`$).

```{r trends, echo=FALSE, fig.show='hide', fig.width=10, fig.height=4, dpi=150}
# fig.show='hide' + a chunk label: the plot file is written to a
# predictable path but not placed -- we place it ourselves in a #figure
# so it gets a caption and can be cross-referenced with @trends.
par(mfrow = c(1, 2), mar = c(4.2, 4.2, 2.5, 1))
plot(mtcars$wt, mtcars$mpg, pch = 19, col = "#0d7377",
     main = "MPG vs. weight", xlab = "Weight (1000 lbs)", ylab = "MPG")
abline(fit, lwd = 2, col = "#1f3a5f")
boxplot(mpg ~ cyl, data = mtcars, col = c("#9ad1d4", "#4f9da6", "#1f3a5f"),
        main = "MPG by cylinder count", xlab = "Cylinders", ylab = "MPG")
```

#figure(
  image("figure/example2/trends-1.png", width: 96%),
  caption: [Fuel economy against weight (left, with fitted line) and by
    cylinder count (right). Heavier, higher-cylinder cars are thirstier.],
) <trends>

As @trends shows, the relationship is strong and close to linear over the
observed range.

#note[
  *Reading note:* the cylinder-count boxplot mostly restates the weight
  effect — heavier cars have more cylinders. Treat these as one finding,
  not two.
]

= Leaderboard

The efficiency podium is a clean sweep for light four-cylinder imports —
every car in the top five weighs under 2,300 lbs.

```{r, echo=FALSE, results='asis'}
# This table is GENERATED BY R: with results='asis', whatever the chunk
# cat()s is treated as Typst markup. The striped rows and rules are three
# lines of Typst (the fill: function below), not a table-package incantation.
top <- head(mtcars[order(-mtcars$mpg), c("mpg", "cyl", "wt")], 5)
cat("#table(\n",
    "  columns: (1fr, auto, auto, auto),\n",
    "  align: (left, right, right, right),\n",
    "  stroke: none,\n",
    "  fill: (_, y) => if calc.odd(y) { luma(246) },\n",
    "  table.hline(stroke: 1pt),\n",
    "  table.header([*Model*], [*MPG*], [*Cylinders*], [*Weight*]),\n",
    "  table.hline(stroke: 0.5pt),\n", sep = "")
for (m in rownames(top)) {
  cat(sprintf("  [%s], [%.1f], [%d], [%.2f],\n",
              m, top[m, "mpg"], top[m, "cyl"], top[m, "wt"]))
}
cat("  table.hline(stroke: 1pt),\n)\n")
```

= Does the transmission matter?

```{r, include=FALSE}
tt <- t.test(mpg ~ am, data = mtcars)
gap <- diff(tt$estimate)
by_am <- aggregate(cbind(mpg, wt) ~ am, data = mtcars, mean)
```

#keyfinding([+`r gap` mpg])[
  Manual-transmission cars average *`r gap` mpg more* than automatics in
  this sample (Welch $t$-test: $t = `r abs(tt$statistic)`$,
  $p = `r tt$p.value`$).
]

Before crowning the stick shift, note the confound: the manual cars here
are also much lighter#footnote[Mean weight `r by_am$wt[2]` vs.
`r by_am$wt[1]` thousand lbs.] -- transmission choice and weight travel together in 1974's lineup.

```{r, echo=FALSE, results='asis'}
lab <- c("Automatic", "Manual")
cat("#table(
",
    "  columns: (1fr, auto, auto),
",
    "  align: (left, right, right),
",
    "  stroke: none,
",
    "  fill: (_, y) => if calc.odd(y) { luma(246) },
",
    "  table.hline(stroke: 1pt),
",
    "  table.header([*Transmission*], [*Mean MPG*], [*Mean weight*]),
",
    "  table.hline(stroke: 0.5pt),
", sep = "")
for (i in seq_len(nrow(by_am))) {
  cat(sprintf("  [%s], [%.1f], [%.2f],
",
              lab[by_am$am[i] + 1], by_am$mpg[i], by_am$wt[i]))
}
cat("  table.hline(stroke: 1pt),
)
")
```

= Discussion

// Two-column text is one function call; the References section below is a
// one-line #bibliography(...) against a plain BibTeX file (see refs.bib).
#columns(2, gutter: 16pt)[
  The efficiency leaders are all light four-cylinder imports; the sample
  mean of $bar(x) = `r mean(mtcars$mpg)`$ mpg is dragged down by a tail
  of heavy V8s, several of which manage barely half that figure.

  For 1974 buyers the advice writes itself: weight, not engineering
  exotica, predicts what you'll spend at the pump. For modern readers,
  the dataset remains a friendly reminder that a single well-chosen
  covariate often explains most of the variance. All computation was
  done in R @rcore.
]

#v(6pt)
#bibliography("refs.bib", style: "apa")
